### ISSUE TITLE
Do some issue related to who want contribute?

### ISSUE THREAD

**Issue by Marlysson** [matclab/pytest-web2py.wip#1]
Could put each part of your planning to separare this feature of your app ..

**Comment by matclab** [comment]
Yes, very good Idea…
I will do that as soon as possible.
Thanks for the suggestion

**Comment by matclab** [comment]
Done with issues #2 to #7.

For now it is expected that people are able to replay *unit* and *web* tests against last web2py code (with the existing README).
I will try to tackle #2 soon, in order to get a better idea of what works well and what is to be improved.
